pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/onlyG19/mingesoProject1']])
                dir("autofix-frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("autofix-frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t byrong/proyecto_autofix_frontend_docker ."
                            bat "docker push byrong/proyecto_autofix_frontend_docker"
                        }
                    }                    
                }
            }
        }
    }
}